title: Legion of Nerds
description: Concerned parents reviewing D65 closure scenarios
theme: just-the-docs

url: https://d65-legionofnerds.github.io

aux_links:
  Legion of Nerds on GitHub: https://github.com/d65-legionofnerds


favicon: /assets/favicon.png